app_name = "auraos"
app_title = "AuraOS"
app_publisher = "Aura Productions"
app_description = (
    "Pipeline, pricing, quotes, jobs and money tracking "
    "for a small video production house"
)
app_email = "anhchung.work@gmail.com"
app_license = "unlicensed"

after_install = "auraos.setup.install.after_install"
after_migrate = "auraos.setup.install.after_migrate"

# Permission gates that no role row can express. Job Task is the one
# doctype crew may read, and what they may read of it depends on the job
# it hangs off - see auraos/auraos/doctype/job_task/job_task.py.
has_permission = {
    "Job Task": "auraos.auraos.doctype.job_task.job_task.has_permission",
}

permission_query_conditions = {
    "Job Task": (
        "auraos.auraos.doctype.job_task.job_task."
        "get_permission_query_conditions"
    ),
}

doc_events = {
    "File": {
        "before_insert": "auraos.attachments.check_attachment_permission",
    },
}

# Doctypes that appear in global search. A doctype absent from this
# hook is invisible in search for everyone; sensitive doctypes are
# listed here deliberately so the permission proof exercises the
# real path (indexed, yet role-filtered).
global_search_doctypes = {
    "Default": [
        {"doctype": "Founder Spike Note"},
        {"doctype": "Party Company"},
        {"doctype": "Party Contact"},
        {"doctype": "Deal"},
        {"doctype": "Job"},
        {"doctype": "Library Document"},
    ]
}

# Job Task is deliberately absent from that list. Global search filters
# by doctype permission, not by document, so indexing it would hand a
# crew session the task titles of every job in the company - the exact
# leak the crew boundary exists to close.

# The app is served at /aura-next from auraos/www/aura-next.html
# (generated by `npm run build` in frontend-react/).
#
# There was a second SPA at /aura, frappe-ui, which this one replaced. It was
# kept reachable as the rollback path while the React app reached parity, and
# #103 retired it once the last route without a counterpart - the deal
# classification SOP - became a Library document instead of a compiled page.
# The Vue sources are in git history if anyone needs to read them; nothing
# serves them.
#
# /quote/<token> is the client-facing quote page (auraos/www/quote.py);
# the token lands in frappe.form_dict.
website_route_rules = [
    {"from_route": "/aura-next/<path:app_path>", "to_route": "aura-next"},
    {"from_route": "/quote/<token>", "to_route": "quote"},
]
