app_name = "auraos"
app_title = "AuraOS"
app_publisher = "Aura Productions"
app_description = (
    "Pipeline, pricing, quotes, jobs and money tracking "
    "for a small video production house"
)
app_email = "anhchung.work@gmail.com"
app_license = "unlicensed"

after_install = "auraos.setup.install.after_install"
after_migrate = "auraos.setup.install.after_migrate"

# Doctypes that appear in global search. A doctype absent from this
# hook is invisible in search for everyone; sensitive doctypes are
# listed here deliberately so the permission proof exercises the
# real path (indexed, yet role-filtered).
global_search_doctypes = {
    "Default": [
        {"doctype": "Founder Spike Note"},
        {"doctype": "Party Company"},
        {"doctype": "Party Contact"},
    ]
}

# The frappe-ui SPA is served at /aura from auraos/www/aura.html
# (generated by `npm run build` in frontend/).
website_route_rules = [
    {"from_route": "/aura/<path:app_path>", "to_route": "aura"},
]
