/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ExpenseRouteImport } from './routes/expense'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ContactsCompaniesRouteImport } from './routes/contacts.companies'
import { Route as ContactsPeopleRouteImport } from './routes/contacts.people'
import { Route as DealsIndexRouteImport } from './routes/deals.index'
import { Route as DealsDealCodeRouteImport } from './routes/deals.$dealCode'
import { Route as DocumentsLibraryRouteImport } from './routes/documents.library'
import { Route as DocumentsPaperworkRouteImport } from './routes/documents.paperwork'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as FinanceAccountsRouteImport } from './routes/finance.accounts'
import { Route as FinanceExpensesRouteImport } from './routes/finance.expenses'
import { Route as FinanceForecastRouteImport } from './routes/finance.forecast'
import { Route as FinanceIncomeRouteImport } from './routes/finance.income'
import { Route as FinanceReceivablesRouteImport } from './routes/finance.receivables'
import { Route as FinanceReportsRouteImport } from './routes/finance.reports'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as QuotationsIndexRouteImport } from './routes/quotations.index'
import { Route as QuotationsQuoteRefRouteImport } from './routes/quotations.$quoteRef'
import { Route as DealsDealCodeIndexRouteImport } from './routes/deals.$dealCode.index'
import { Route as DealsDealCodeQuoteRouteImport } from './routes/deals.$dealCode.quote'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseRoute = ExpenseRouteImport.update({
  id: '/expense',
  path: '/expense',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsCompaniesRoute = ContactsCompaniesRouteImport.update({
  id: '/contacts/companies',
  path: '/contacts/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsPeopleRoute = ContactsPeopleRouteImport.update({
  id: '/contacts/people',
  path: '/contacts/people',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIndexRoute = DealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsDealCodeRoute = DealsDealCodeRouteImport.update({
  id: '/deals/$dealCode',
  path: '/deals/$dealCode',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsLibraryRoute = DocumentsLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => DocumentsRoute,
} as any)
const DocumentsPaperworkRoute = DocumentsPaperworkRouteImport.update({
  id: '/paperwork',
  path: '/paperwork',
  getParentRoute: () => DocumentsRoute,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceAccountsRoute = FinanceAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceExpensesRoute = FinanceExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceForecastRoute = FinanceForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceIncomeRoute = FinanceIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceReceivablesRoute = FinanceReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceReportsRoute = FinanceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => FinanceRoute,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsIndexRoute = QuotationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuotationsRoute,
} as any)
const QuotationsQuoteRefRoute = QuotationsQuoteRefRouteImport.update({
  id: '/$quoteRef',
  path: '/$quoteRef',
  getParentRoute: () => QuotationsRoute,
} as any)
const DealsDealCodeIndexRoute = DealsDealCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DealsDealCodeRoute,
} as any)
const DealsDealCodeQuoteRoute = DealsDealCodeQuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => DealsDealCodeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/expense': typeof ExpenseRoute
  '/finance': typeof FinanceRouteWithChildren
  '/quotations': typeof QuotationsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/contacts/companies': typeof ContactsCompaniesRoute
  '/contacts/people': typeof ContactsPeopleRoute
  '/deals/$dealCode': typeof DealsDealCodeRouteWithChildren
  '/documents/library': typeof DocumentsLibraryRoute
  '/documents/paperwork': typeof DocumentsPaperworkRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/forecast': typeof FinanceForecastRoute
  '/finance/income': typeof FinanceIncomeRoute
  '/finance/receivables': typeof FinanceReceivablesRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/quotations/$quoteRef': typeof QuotationsQuoteRefRoute
  '/deals/': typeof DealsIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/quotations/': typeof QuotationsIndexRoute
  '/deals/$dealCode/quote': typeof DealsDealCodeQuoteRoute
  '/deals/$dealCode/': typeof DealsDealCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/expense': typeof ExpenseRoute
  '/settings': typeof SettingsRoute
  '/contacts/companies': typeof ContactsCompaniesRoute
  '/contacts/people': typeof ContactsPeopleRoute
  '/documents/library': typeof DocumentsLibraryRoute
  '/documents/paperwork': typeof DocumentsPaperworkRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/forecast': typeof FinanceForecastRoute
  '/finance/income': typeof FinanceIncomeRoute
  '/finance/receivables': typeof FinanceReceivablesRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/quotations/$quoteRef': typeof QuotationsQuoteRefRoute
  '/deals': typeof DealsIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/quotations': typeof QuotationsIndexRoute
  '/deals/$dealCode/quote': typeof DealsDealCodeQuoteRoute
  '/deals/$dealCode': typeof DealsDealCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/expense': typeof ExpenseRoute
  '/finance': typeof FinanceRouteWithChildren
  '/quotations': typeof QuotationsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/contacts/companies': typeof ContactsCompaniesRoute
  '/contacts/people': typeof ContactsPeopleRoute
  '/deals/$dealCode': typeof DealsDealCodeRouteWithChildren
  '/documents/library': typeof DocumentsLibraryRoute
  '/documents/paperwork': typeof DocumentsPaperworkRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/forecast': typeof FinanceForecastRoute
  '/finance/income': typeof FinanceIncomeRoute
  '/finance/receivables': typeof FinanceReceivablesRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/quotations/$quoteRef': typeof QuotationsQuoteRefRoute
  '/deals/': typeof DealsIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/quotations/': typeof QuotationsIndexRoute
  '/deals/$dealCode/quote': typeof DealsDealCodeQuoteRoute
  '/deals/$dealCode/': typeof DealsDealCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documents'
    | '/expense'
    | '/finance'
    | '/quotations'
    | '/settings'
    | '/contacts/companies'
    | '/contacts/people'
    | '/deals/$dealCode'
    | '/documents/library'
    | '/documents/paperwork'
    | '/finance/accounts'
    | '/finance/expenses'
    | '/finance/forecast'
    | '/finance/income'
    | '/finance/receivables'
    | '/finance/reports'
    | '/jobs/$jobId'
    | '/quotations/$quoteRef'
    | '/deals/'
    | '/finance/'
    | '/jobs/'
    | '/quotations/'
    | '/deals/$dealCode/quote'
    | '/deals/$dealCode/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documents'
    | '/expense'
    | '/settings'
    | '/contacts/companies'
    | '/contacts/people'
    | '/documents/library'
    | '/documents/paperwork'
    | '/finance/accounts'
    | '/finance/expenses'
    | '/finance/forecast'
    | '/finance/income'
    | '/finance/receivables'
    | '/finance/reports'
    | '/jobs/$jobId'
    | '/quotations/$quoteRef'
    | '/deals'
    | '/finance'
    | '/jobs'
    | '/quotations'
    | '/deals/$dealCode/quote'
    | '/deals/$dealCode'
  id:
    | '__root__'
    | '/'
    | '/documents'
    | '/expense'
    | '/finance'
    | '/quotations'
    | '/settings'
    | '/contacts/companies'
    | '/contacts/people'
    | '/deals/$dealCode'
    | '/documents/library'
    | '/documents/paperwork'
    | '/finance/accounts'
    | '/finance/expenses'
    | '/finance/forecast'
    | '/finance/income'
    | '/finance/receivables'
    | '/finance/reports'
    | '/jobs/$jobId'
    | '/quotations/$quoteRef'
    | '/deals/'
    | '/finance/'
    | '/jobs/'
    | '/quotations/'
    | '/deals/$dealCode/quote'
    | '/deals/$dealCode/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentsRoute: typeof DocumentsRouteWithChildren
  ExpenseRoute: typeof ExpenseRoute
  FinanceRoute: typeof FinanceRouteWithChildren
  QuotationsRoute: typeof QuotationsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ContactsCompaniesRoute: typeof ContactsCompaniesRoute
  ContactsPeopleRoute: typeof ContactsPeopleRoute
  DealsDealCodeRoute: typeof DealsDealCodeRouteWithChildren
  JobsJobIdRoute: typeof JobsJobIdRoute
  DealsIndexRoute: typeof DealsIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense': {
      id: '/expense'
      path: '/expense'
      fullPath: '/expense'
      preLoaderRoute: typeof ExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/companies': {
      id: '/contacts/companies'
      path: '/contacts/companies'
      fullPath: '/contacts/companies'
      preLoaderRoute: typeof ContactsCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/people': {
      id: '/contacts/people'
      path: '/contacts/people'
      fullPath: '/contacts/people'
      preLoaderRoute: typeof ContactsPeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/': {
      id: '/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof DealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$dealCode': {
      id: '/deals/$dealCode'
      path: '/deals/$dealCode'
      fullPath: '/deals/$dealCode'
      preLoaderRoute: typeof DealsDealCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/library': {
      id: '/documents/library'
      path: '/library'
      fullPath: '/documents/library'
      preLoaderRoute: typeof DocumentsLibraryRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/paperwork': {
      id: '/documents/paperwork'
      path: '/paperwork'
      fullPath: '/documents/paperwork'
      preLoaderRoute: typeof DocumentsPaperworkRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/accounts': {
      id: '/finance/accounts'
      path: '/accounts'
      fullPath: '/finance/accounts'
      preLoaderRoute: typeof FinanceAccountsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/expenses': {
      id: '/finance/expenses'
      path: '/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof FinanceExpensesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/forecast': {
      id: '/finance/forecast'
      path: '/forecast'
      fullPath: '/finance/forecast'
      preLoaderRoute: typeof FinanceForecastRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/income': {
      id: '/finance/income'
      path: '/income'
      fullPath: '/finance/income'
      preLoaderRoute: typeof FinanceIncomeRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/receivables': {
      id: '/finance/receivables'
      path: '/receivables'
      fullPath: '/finance/receivables'
      preLoaderRoute: typeof FinanceReceivablesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/reports': {
      id: '/finance/reports'
      path: '/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof FinanceReportsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations/': {
      id: '/quotations/'
      path: '/'
      fullPath: '/quotations/'
      preLoaderRoute: typeof QuotationsIndexRouteImport
      parentRoute: typeof QuotationsRoute
    }
    '/quotations/$quoteRef': {
      id: '/quotations/$quoteRef'
      path: '/$quoteRef'
      fullPath: '/quotations/$quoteRef'
      preLoaderRoute: typeof QuotationsQuoteRefRouteImport
      parentRoute: typeof QuotationsRoute
    }
    '/deals/$dealCode/': {
      id: '/deals/$dealCode/'
      path: '/'
      fullPath: '/deals/$dealCode/'
      preLoaderRoute: typeof DealsDealCodeIndexRouteImport
      parentRoute: typeof DealsDealCodeRoute
    }
    '/deals/$dealCode/quote': {
      id: '/deals/$dealCode/quote'
      path: '/quote'
      fullPath: '/deals/$dealCode/quote'
      preLoaderRoute: typeof DealsDealCodeQuoteRouteImport
      parentRoute: typeof DealsDealCodeRoute
    }
  }
}

interface DocumentsRouteChildren {
  DocumentsLibraryRoute: typeof DocumentsLibraryRoute
  DocumentsPaperworkRoute: typeof DocumentsPaperworkRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsLibraryRoute: DocumentsLibraryRoute,
  DocumentsPaperworkRoute: DocumentsPaperworkRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

interface FinanceRouteChildren {
  FinanceAccountsRoute: typeof FinanceAccountsRoute
  FinanceExpensesRoute: typeof FinanceExpensesRoute
  FinanceForecastRoute: typeof FinanceForecastRoute
  FinanceIncomeRoute: typeof FinanceIncomeRoute
  FinanceReceivablesRoute: typeof FinanceReceivablesRoute
  FinanceReportsRoute: typeof FinanceReportsRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceAccountsRoute: FinanceAccountsRoute,
  FinanceExpensesRoute: FinanceExpensesRoute,
  FinanceForecastRoute: FinanceForecastRoute,
  FinanceIncomeRoute: FinanceIncomeRoute,
  FinanceReceivablesRoute: FinanceReceivablesRoute,
  FinanceReportsRoute: FinanceReportsRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface QuotationsRouteChildren {
  QuotationsQuoteRefRoute: typeof QuotationsQuoteRefRoute
  QuotationsIndexRoute: typeof QuotationsIndexRoute
}

const QuotationsRouteChildren: QuotationsRouteChildren = {
  QuotationsQuoteRefRoute: QuotationsQuoteRefRoute,
  QuotationsIndexRoute: QuotationsIndexRoute,
}

const QuotationsRouteWithChildren = QuotationsRoute._addFileChildren(
  QuotationsRouteChildren,
)

interface DealsDealCodeRouteChildren {
  DealsDealCodeQuoteRoute: typeof DealsDealCodeQuoteRoute
  DealsDealCodeIndexRoute: typeof DealsDealCodeIndexRoute
}

const DealsDealCodeRouteChildren: DealsDealCodeRouteChildren = {
  DealsDealCodeQuoteRoute: DealsDealCodeQuoteRoute,
  DealsDealCodeIndexRoute: DealsDealCodeIndexRoute,
}

const DealsDealCodeRouteWithChildren = DealsDealCodeRoute._addFileChildren(
  DealsDealCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentsRoute: DocumentsRouteWithChildren,
  ExpenseRoute: ExpenseRoute,
  FinanceRoute: FinanceRouteWithChildren,
  QuotationsRoute: QuotationsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ContactsCompaniesRoute: ContactsCompaniesRoute,
  ContactsPeopleRoute: ContactsPeopleRoute,
  DealsDealCodeRoute: DealsDealCodeRouteWithChildren,
  JobsJobIdRoute: JobsJobIdRoute,
  DealsIndexRoute: DealsIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
